language: csharp
solution: API.sln
os: linux

group: travis_latest

mono: none
dotnet: 3.0

branches:
  only:
  - master
  - release
  - dev

install:
    dotnet restore src/API.Web/API.Web.csproj

script:
  - dotnet test

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh latest
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh release
    on:
      branch: release
