language: csharp
solution: API.sln
os: linux

group: travis_latest

mono: none
dotnet: 3.0

branches:
  only:
  - master
  - release
  - dev

install:
    dotnet restore src/API.Web/API.Web.csproj

script:
  - dotnet test

deploy:
  - provider: script
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t launc .
    - docker images
    - docker tag launc:latest $DOCKER_USERNAME/launc-backend
    - docker push $DOCKER_USERNAME/launc-backend
    on:
      branch: master

  - provider: script
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t launc .
    - docker images
    - docker tag launc:release $DOCKER_USERNAME/launc-backend
    - docker push $DOCKER_USERNAME/launc-backend
    on:
      branch: release

