FROM mcr.microsoft.com/dotnet/core/sdk:3.0
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./*.sln ./
COPY ./src/API.Web/API.Web.csproj ./API.Web.csproj
RUN dotnet restore API.Web.csproj

COPY . ./

ENV PATH="${PATH}:/root/.dotnet/tools"

# Install the Dotnet entity framework so we can run migrations
RUN dotnet tool install --global dotnet-ef --version 3.0.0

EXPOSE 5000

RUN chmod +x ./scripts/wait-for-it.sh
RUN chmod +x ./scripts/local-entrypoint.sh
ENTRYPOINT ./scripts/wait-for-it.sh database:5432 -- ./scripts/local-entrypoint.sh
